name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hello world print
      run: echo Hello, world!
    - name: print dir
      run: ls -al
    - name: print python version
      run: python -V
  
